version: '3.1'

services:

  # mongo:
  #   image: mongo
  #   volumes:
  #     - ./data/runtime/db:/data/db
  #   command: mongod --smallfiles --oplogSize 128

  scanner:
    image: id-scanner:latest
    # environment:
    #   - PORT=3000
    #   - MONGO_URL=mongodb://mongo:27017/identities
    # links:
    #   - mongo:mongo
    expose:
      - "3000"

  nginx:
    image: nginx
    volumes:
      - ./scanner.conf:/etc/nginx/conf.d/default.conf
    links:
      - scanner
    ports:
      - "80:80"
